### ISSUE TITLE
Dose 1.5.3 x86 apk support？

### ISSUE THREAD

**Issue by bemoons** [codehz/mcpeserver#36]
I got ERROR：
Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR9WhitelistRK7OpsListP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsRN9minecraft3api3ApiEibiiibRKSt6vectorISsSaISsEESsRKN3mce4UUIDER17MinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS13_EER9SchedulerEERKSsP9LevelDataPSZ_S11_IFvS1C_EES1H_

**Comment by bemoons** [comment]
Thanks for your quickly response！
I'm using Ubuntu 16.04. Could you update the source code?

**Comment by codehz** [comment]
@bemoons I don't want to maintain many different versions for it... And I think upgrade the system version is a better choice.

**Comment by Teages** [comment]
I found something wrong when I try to install minecraft-core_0.1.0 in my Ubuntu server(18.04).
The error massage:
```
ubuntu@VM-0-17-ubuntu:~$ sudo dpkg -i mcpeserver-core_0.1.0_amd64.deb
(Reading database ... 127073 files and directories currently installed.)
Preparing to unpack mcpeserver-core_0.1.0_amd64.deb ...
Unpacking mcpeserver-core (0.1.0) over (0.1.0) ...
dpkg: dependency problems prevent configuration of mcpeserver-core:
 mcpeserver-core depends on dbus-user-session; however:
  Package dbus-user-session is not installed.
 mcpeserver-core depends on libsystemd0:i386 (>= 237); however:

dpkg: error processing package mcpeserver-core (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 mcpeserver-core

```
May be I did something wrong?

**Comment by codehz** [comment]
@Teages 
```
sudo dpkg -i mcpeserver-core_0.1.0_amd64.deb
dpkg --add-architecture i386
sudo apt-get install -f
```

**Comment by database64128** [comment]
Will CentOS 7 support be added in the future? I manage several CentOS 7 VMs as Bedrock servers and it would be very inconvenient if newer server versions had no CentOS 7 support.

**Comment by codehz** [comment]
@database64128 well, I think it is possible, just compile it and codehz/bedrockserver in CentOS, but packaging is harder than comping... I think I will provide a docker image in future

**Comment by Teages** [comment]
Oh,it worked.
Think you very much for your great work, @codehz .
The server runs very well.
A suggest for someone who have some problem with the keyword "lib":
```
sudo apt-get install lib32stdc++6
sudo apt-get install lib32z1
```

**Comment by quizhizhe** [comment]
Don't have access to https://dl.codehz.one/repo/ubuntu/, 404, not found

**Comment by codehz** [comment]
@quizhizhe It has been removed temporarily. and may be re-added in recent

**Comment by quizhizhe** [comment]
Well, I'll be waiting it

**Comment by derray** [comment]
I'd love to see the Ubuntu/Debian package too!
Thanks for the awesome work.

**Comment by Jurjeee** [comment]
Indeed great work on this project! As above, I'd love to see a Ubuntu package too.

**Comment by codehz** [comment]
@quizhizhe @derray @Jurjeee Can you help me to testing the ubuntu building?

Note that this is not the final package, just for testing purposes.

1. download `https://cdn.codehz.one/temp/ubuntu-testing.tar.bz2` and extract it to any where
2. create a file in /etc/dbus-1/systemd/test.conf
```XML
<!DOCTYPE busconfig PUBLIC
 "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
        <policy user="XXXXXX">
                <allow own_prefix="one.codehz.bedrockserver"/>
        </policy>
        <policy group="mcpeserver">
                <allow own_prefix="one.codehz.bedrockserver"/>
        </policy>
        <policy context="default">
                <deny own_prefix="one.codehz.bedrockserver"/>
		<allow receive_path="/one/codehz/bedrockserver" receive_interface="*" eavesdrop="true" />
		<allow send_path="/one/codehz/bedrockserver" send_interface="*" />
		<allow send_interface="one.codehz.bedrockserver.core" />
		<allow receive_interface="one.codehz.bedrockserver.core" />
		<allow send_interface="one.codehz.bedrockserver.chat" />
        </policy>
</busconfig>
 ```
you should replace XXXXXX with your username(linux).

3. execute `systemctl reload dbus`
4. put minecraft 1.6.0.14 apk to current directory 
5. execute `./mcpeserver unpack --apk filename.apk`
6. execute `./mcpeserver run` to testing

**Comment by derray** [comment]
Of course, I'll test it asap.

**Comment by quizhizhe** [comment]
Of course!

**Comment by Jurjeee** [comment]
@codehz I'm testing it right now. I should have sent you a mail regarding an unrelated issue with the code.

**Comment by Jurjeee** [comment]
I've ran into the following:
![image](https://user-images.githubusercontent.com/5147593/44842435-1da76d00-ac46-11e8-9e8b-4ad6c2bc8308.png)

@quizhizhe @derray Are you guys running into a similar problem?

**Comment by codehz** [comment]
@Jurjeee try to 
```shell
strace -e file -f -o test.txt ./bin/bedrockserver
```
then run
```shell
cat test.txt | grep -oP '[^"]+\.so[^"]*' | sort | uniq
```
paste the output

**Comment by quizhizhe** [comment]
root@iZwz906kmfgcyh3r0ujk89Z:~/mcpeservser# ./mcpeserver run
I [core] Loading profile: default
W [core] Config file is not exists, creating...
N [core] Loading Bridge...
I [core] Bridge Version: 0.1.6
I [core] Request DBUS Name: one.codehz.bedrockserver.default
I [DBUS] Starting...
I [DBUS] Stoping...
E [DBUS] Permission denied
mcpe://root@iZwz906kmfgcyh3r0ujk89Z$
@codehz

**Comment by codehz** [comment]
@quizhizhe paste  /etc/dbus-1/systemd/test.conf

**Comment by Jurjeee** [comment]
@codehz 
![image](https://user-images.githubusercontent.com/5147593/44843580-e8504e80-ac48-11e8-9835-426f3a97b548.png)

@quizhizhe I had the same issue on Archlinux.

**Comment by codehz** [comment]
@Jurjeee try to install liblzma5:i386 libgcrypt20:i386 libgpg-error0:i386 libc6:i386

**Comment by derray** [comment]
isn't it:
"/etc/dbus-1/system.d/test.conf" ?
instead of:
"/etc/dbus-1/systemd/test.conf"

**Comment by codehz** [comment]
@derray I think it is typo....
using /etc/dbus-1/system.d/test.conf

**Comment by derray** [comment]
`ray@ray-desktop:~/Downloads/bedrockserver/server$ ./mcpeserver run
I [core] Loading profile: default
W [core] Config file is not exists, creating...
N [core] Loading Bridge...
I [core] Bridge Version: 0.1.6
I [core] Request DBUS Name: one.codehz.bedrockserver.default
I [DBUS] Starting...
N [core] Loading Bedrock Server...
D [Bridge] Minecraft is at offset 0xf3198000
I [Bridge] Game version: 1.6.0
T [AppPlatform] Vtable size = 241
I [Bridge] Applying patches
T [AppPlatform] createDeviceID: 
T [Bridge] Loading server properties
T [AppPlatform] getCurrentStoragePath: /home/ray/Downloads/bedrockserver/server/data
T [Bridge] Initializing resource loaders
T [AppPlatform] getSystemRegion: 0xdeadbeef
T [Bridge] Initializing ResourcePackManager
T [Bridge] Initializing PackManifestFactory
T [Bridge] Initializing SkinPackKeyProvider
T [Bridge] Initializing PackSourceFactory
T [Bridge] Initializing ResourcePackRepository
T [AppPlatform] getInternalStoragePath: /home/ray/Downloads/bedrockserver/server/data
T [AppPlatform] getInternalStoragePath: /home/ray/Downloads/bedrockserver/server/data
T [AppPlatform] getInternalStoragePath: /home/ray/Downloads/bedrockserver/server/data
T [AppPlatform] getInternalStoragePath: /home/ray/Downloads/bedrockserver/server/data
T [AppPlatform] getInternalStoragePath: /home/ray/Downloads/bedrockserver/server/data
T [AppPlatform] getInternalStoragePath: /home/ray/Downloads/bedrockserver/server/data
T [AppPlatform] getInternalStoragePath: /home/ray/Downloads/bedrockserver/server/data
T [Bridge] Adding vanilla resource pack
T [Bridge] Adding world resource packs
D [Bridge] Initializing SaveTransactionManager
D [Bridge] Initializing ExternalFileLevelStorageSource
D [Bridge] Initializing ServerInstance
W [Minecraft] NO LOG FILE! - IPv6 supported, port: 19133
W [Minecraft] NO LOG FILE! - IPv4 supported, port: 19132
T [Bridge] Loading language data
I [Bridge] Server initialized
mcpe://ray@ray-desktop$  
`

**Comment by codehz** [comment]
@derray I think it is work

**Comment by derray** [comment]
Thanks, seems to work, at the first look! =)
i'm at work, but i'll take a break soon, then i'll give it a try.

**Comment by codehz** [comment]
@Jurjeee you can download https://cdn.codehz.one/temp/ubuntu-testing.tar.bz2 , and try again
It has been updated

**Comment by quizhizhe** [comment]
0mI [core] Loading profile: default^M^[[0m
^[[0mW [core] Config file is not exists, creating...^M^[[0m
^[[0mN [core] Loading Bridge...^M^[[0m
^[[0mI [core] Bridge Version: 0.1.6^M^[[0m
^[[0mI [core] Request DBUS Name: one.codehz.bedrockserver.default^M^[[0m
^[[0mI [DBUS] Starting...^M^[[0m
^[[0mN [core] Loading Bedrock Server...^[[0m
^[[0mF [dumper] Signal 11 received^[[0m
^[[0mF [dumper] Backtrace Count: 8^[[0m
^[[0mF [dumper] #0 ./bin/bedrockserver(+0x1e4ef) [0x566174ef]^[[0m
^[[0mF [dumper] #1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f4e070]^[[0m
^[[0mF [dumper] #2 ./bin/bedrockserver(+0xc790) [0x56605790]^[[0m
^[[0mF [dumper] #3 ./bin/bedrockserver(+0xd03d) [0x5660603d]^[[0m
^[[0mF [dumper] #4 ./bin/bedrockserver(+0xcddd) [0x56605ddd]^[[0m
^[[0mF [dumper] #5 ./bin/bedrockserver(+0xbd1d) [0x56604d1d]^[[0m
^[[0mF [dumper] #6 ./lib/libc.so.6(__libc_start_main+0xf1) [0xf7ae5b41]^[[0m
^[[0mF [dumper] #7 ./bin/bedrockserver(+0xbd5b) [0x56604d5b]^[[0m
^[[0mF [dumper] Dumping stack...^[[0m

**Comment by codehz** [comment]
@quizhizhe checking your ./data folder

**Comment by quizhizhe** [comment]
no ./data

**Comment by codehz** [comment]
@quizhizhe ....
do you actually read the instruction? 

put minecraft release 1.6 apk to current directory
execute `./mcpeserver unpack --apk filename.apk`

**Comment by quizhizhe** [comment]
Oh! @corehz Thanks! it's work. But the /kill @s have a bug. If you used it, you will be killed over and over again.

**Comment by derray** [comment]
@Jurjeee 

> I've ran into the following:
image
@quizhizhe @derray Are you guys running into a similar problem?

yes, just do the following:
```
sudo dpkg --add-architecture i386
sudo apt update
sudo apt install liblzma5:i386 libgcrypt20:i386 libgpg-error0:i386 libc6:i386
```
this should do the trick.

And don't forget to `sudo systemctl reload dbus` after adding the /etc/dbus-1/system.d/test.conf

**Comment by codehz** [comment]
@derray I think it may be not required now, I fixed the problem

**Comment by derray** [comment]
Nice to hear! Btw. it's running on Debian 9.

**Comment by Jurjeee** [comment]
@codehz Still the same with the new build. If I try the other command you suggested I get the following:
![image](https://user-images.githubusercontent.com/5147593/44853299-dcbf5080-ac65-11e8-8a42-150b8489838d.png)

**Comment by codehz** [comment]
@Jurjeee I think you should definitely forgot to unpack the app with ./mcpeserver unpack --apk xxxx
Ps: DO NOT UNPACK DIRECTLY

**Comment by Jurjeee** [comment]
I've removed the whole folder and did all the steps again. Now it working.

**Comment by codehz** [comment]
@quizhizhe @derray @Jurjeee 
The installation script is done! see https://gist.github.com/codehz/610bdeba96fcec16e6339abae7208e7d 
Tip: you can get wget-able url by click RAW button
